### PR TITLE
Kafka Example Files

### PR DESCRIPTION
**Pull request by plutowootoe**
Some amazonMSK Test files

### CODE REVIEW

**Review by oakwoodwolf — DISMISSED** [review]
Looks fine to me. No errors.

**Review by Blake1412 — CHANGES_REQUESTED** [review]
Can you remove the .idea folder, add it to the gitignore

**Comment by plutowootoe** [comment]
Added change

**Review by oakwoodwolf — CHANGES_REQUESTED** [review]
The gradle root seems to be the project folder, shouldn't the gitignore for this also be in the project folder?

**Pull request merged**
