### PR TITLE
database microservice

### PR DESCRIPTION
**Pull request by Blake1412**
CD into database folder, run ./gradlew build 
Run docker compose up
Will launch Spring Boot CRUD application on http://localhost:8080
See controller files for endpoints

examples:

POST http://localhost:8080/users/create 
Body: {
  "email": "test@gmail.com",
    "password": "test",
    "name": "testing",
    "profilePicture": "default"
}

GET http://localhost:8080/users/id?id=1

### CODE REVIEW

**Comment by oakwoodwolf** [comment]
Can you set it to a seperate port? chat uses 8080 and security uses 8081. maybe 8082?

**Review by Bojo992 — APPROVED** [review]
lgtm

**Review by oakwoodwolf — APPROVED** [review]
spring-boot-app should be renamed but implementation works.

**Review by plutowootoe — COMMENTED** [review]
Good job!

**Pull request merged**
